server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-name: oauth2-client-app
            client-id: oauth2-client-app
            client-secret: 'client secret'
            redirect-uri: http://localhost:8081/login/v1/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - openid
              - profile
              - email
            provider: keycloak
          keycloakWithPKCE:
            client-name: oauth2-client-app2
            client-id: oauth2-client-app2
            client-secret: 'client secret'
            redirect-uri: http://localhost:8081/login/v1/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: none
            scope:
              - openid
              - profile
              - email
            provider: keycloak
          keycloak2:
            client-name: oauth2-client-app3
            client-id: oauth2-client-app3
            client-secret: 'client secret'
            redirect-uri: http://localhost:80801/home
            authorization-grant-type: implicit
            client-authentication-method: none
            scope:
              - openid
              - profile
              - email
            provider: keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost:18080/realms/master/protocol/openid-connect/auth
            token-uri: http://localhost:18080/realms/master/protocol/openid-connect/token
            issuer-uri: http://localhost:18080/realms/master
            user-info-uri: http://localhost:18080/realms/master/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:18080/realms/master/protocol/openid-connect/certs
            user-name-attribute: preferred_username